import ThresholdComponentScores

-- Types and transitive kernel axioms for every explicit theorem in the release.
#check ThresholdComponentScores.Thresholds.bin_monotone
#print axioms ThresholdComponentScores.Thresholds.bin_monotone
#check ThresholdComponentScores.Thresholds.bin_max
#print axioms ThresholdComponentScores.Thresholds.bin_max
#check ThresholdComponentScores.Thresholds.bin_sup'
#print axioms ThresholdComponentScores.Thresholds.bin_sup'
#check ThresholdComponentScores.Thresholds.bin_sup
#print axioms ThresholdComponentScores.Thresholds.bin_sup
#check ThresholdComponentScores.Thresholds.break_le_iff
#print axioms ThresholdComponentScores.Thresholds.break_le_iff
#check ThresholdComponentScores.Thresholds.state_eq_none_iff
#print axioms ThresholdComponentScores.Thresholds.state_eq_none_iff
#check ThresholdComponentScores.Thresholds.state_eq_some_iff
#print axioms ThresholdComponentScores.Thresholds.state_eq_some_iff
#check ThresholdComponentScores.Thresholds.state_eq_state_iff
#print axioms ThresholdComponentScores.Thresholds.state_eq_state_iff
#check ThresholdComponentScores.Thresholds.bin_eq_iff
#print axioms ThresholdComponentScores.Thresholds.bin_eq_iff
#check ThresholdComponentScores.Thresholds.bin_breakpoint
#print axioms ThresholdComponentScores.Thresholds.bin_breakpoint
#check ThresholdComponentScores.Thresholds.bin_zero
#print axioms ThresholdComponentScores.Thresholds.bin_zero
#check ThresholdComponentScores.Thresholds.lower_le_iff
#print axioms ThresholdComponentScores.Thresholds.lower_le_iff
#check ThresholdComponentScores.Thresholds.state_eq_some_cell
#print axioms ThresholdComponentScores.Thresholds.state_eq_some_cell
#check ThresholdComponentScores.Thresholds.allowed_none_iff
#print axioms ThresholdComponentScores.Thresholds.allowed_none_iff
#check ThresholdComponentScores.Thresholds.allowed_some_iff
#print axioms ThresholdComponentScores.Thresholds.allowed_some_iff
#check ThresholdComponentScores.Thresholds.allowed_some_below_iff
#print axioms ThresholdComponentScores.Thresholds.allowed_some_below_iff
#check ThresholdComponentScores.Thresholds.allowed_some_top_iff
#print axioms ThresholdComponentScores.Thresholds.allowed_some_top_iff
#check ThresholdComponentScores.Thresholds.representative_spec
#print axioms ThresholdComponentScores.Thresholds.representative_spec
#check ThresholdComponentScores.mem_component
#print axioms ThresholdComponentScores.mem_component
#check ThresholdComponentScores.mem_components
#print axioms ThresholdComponentScores.mem_components
#check ThresholdComponentScores.component_subset_active
#print axioms ThresholdComponentScores.component_subset_active
#check ThresholdComponentScores.mem_component_self
#print axioms ThresholdComponentScores.mem_component_self
#check ThresholdComponentScores.component_nonempty
#print axioms ThresholdComponentScores.component_nonempty
#check ThresholdComponentScores.component_mem_components
#print axioms ThresholdComponentScores.component_mem_components
#check ThresholdComponentScores.components_nonempty
#print axioms ThresholdComponentScores.components_nonempty
#check ThresholdComponentScores.components_subset_active
#print axioms ThresholdComponentScores.components_subset_active
#check ThresholdComponentScores.mem_component_iff_reachable
#print axioms ThresholdComponentScores.mem_component_iff_reachable
#check ThresholdComponentScores.component_eq_of_reachable
#print axioms ThresholdComponentScores.component_eq_of_reachable
#check ThresholdComponentScores.component_eq_iff_reachable
#print axioms ThresholdComponentScores.component_eq_iff_reachable
#check ThresholdComponentScores.components_cover
#print axioms ThresholdComponentScores.components_cover
#check ThresholdComponentScores.components_eq_of_mem
#print axioms ThresholdComponentScores.components_eq_of_mem
#check ThresholdComponentScores.components_disjoint_or_eq
#print axioms ThresholdComponentScores.components_disjoint_or_eq
#check ThresholdComponentScores.activeGraph_mono
#print axioms ThresholdComponentScores.activeGraph_mono
#check ThresholdComponentScores.component_mono
#print axioms ThresholdComponentScores.component_mono
#check ThresholdComponentScores.component_subset_unique
#print axioms ThresholdComponentScores.component_subset_unique
#check ThresholdComponentScores.subset_component_iff
#print axioms ThresholdComponentScores.subset_component_iff
#check ThresholdComponentScores.mem_component_iff_connectedComponent
#print axioms ThresholdComponentScores.mem_component_iff_connectedComponent
#check ThresholdComponentScores.reachable_induce_iff
#print axioms ThresholdComponentScores.reachable_induce_iff
#check ThresholdComponentScores.components_pairwise_reachable
#print axioms ThresholdComponentScores.components_pairwise_reachable
#check ThresholdComponentScores.components_maximal
#print axioms ThresholdComponentScores.components_maximal
#check ThresholdComponentScores.mem_components_iff_maximal
#print axioms ThresholdComponentScores.mem_components_iff_maximal
#check ThresholdComponentScores.components_empty
#print axioms ThresholdComponentScores.components_empty
#check ThresholdComponentScores.Instance.mem_active
#print axioms ThresholdComponentScores.Instance.mem_active
#check ThresholdComponentScores.Instance.stateActive_stateOf
#print axioms ThresholdComponentScores.Instance.stateActive_stateOf
#check ThresholdComponentScores.Instance.score_eq_stateScore
#print axioms ThresholdComponentScores.Instance.score_eq_stateScore
#check ThresholdComponentScores.Instance.mem_box_iff
#print axioms ThresholdComponentScores.Instance.mem_box_iff
#check ThresholdComponentScores.Instance.baseline_mem_box
#print axioms ThresholdComponentScores.Instance.baseline_mem_box
#check ThresholdComponentScores.Instance.stateOf_mem_allowedStates
#print axioms ThresholdComponentScores.Instance.stateOf_mem_allowedStates
#check ThresholdComponentScores.Instance.liftState_spec
#print axioms ThresholdComponentScores.Instance.liftState_spec
#check ThresholdComponentScores.Instance.stateOf_surjOn
#print axioms ThresholdComponentScores.Instance.stateOf_surjOn
#check ThresholdComponentScores.Instance.scoreImage_eq_stateImage
#print axioms ThresholdComponentScores.Instance.scoreImage_eq_stateImage
#check ThresholdComponentScores.Instance.scoreImage_finite
#print axioms ThresholdComponentScores.Instance.scoreImage_finite
#check ThresholdComponentScores.Instance.scoreImage_nonempty
#print axioms ThresholdComponentScores.Instance.scoreImage_nonempty
#check ThresholdComponentScores.Instance.attained_extrema
#print axioms ThresholdComponentScores.Instance.attained_extrema
#check ThresholdComponentScores.Instance.scoreImage_has_endpoints
#print axioms ThresholdComponentScores.Instance.scoreImage_has_endpoints
#check ThresholdComponentScores.Instance.largest_absolute_error
#print axioms ThresholdComponentScores.Instance.largest_absolute_error
#check ThresholdComponentScores.Instance.tau_mem_thresholdValues
#print axioms ThresholdComponentScores.Instance.tau_mem_thresholdValues
#check ThresholdComponentScores.Instance.break_mem_thresholdValues
#print axioms ThresholdComponentScores.Instance.break_mem_thresholdValues
#check ThresholdComponentScores.Instance.distance_mem_criticalDistances
#print axioms ThresholdComponentScores.Instance.distance_mem_criticalDistances
#check ThresholdComponentScores.Instance.criticalDistances_nonneg
#print axioms ThresholdComponentScores.Instance.criticalDistances_nonneg
#check ThresholdComponentScores.Instance.RadiusCell.nonneg
#print axioms ThresholdComponentScores.Instance.RadiusCell.nonneg
#check ThresholdComponentScores.Instance.RadiusCell.comparisons
#print axioms ThresholdComponentScores.Instance.RadiusCell.comparisons
#check ThresholdComponentScores.Instance.endpoint_comparisons
#print axioms ThresholdComponentScores.Instance.endpoint_comparisons
#check ThresholdComponentScores.Instance.allowed_cell_constant
#print axioms ThresholdComponentScores.Instance.allowed_cell_constant
#check ThresholdComponentScores.Instance.allowedStates_cell_constant
#print axioms ThresholdComponentScores.Instance.allowedStates_cell_constant
#check ThresholdComponentScores.Instance.scoreImage_cell_constant
#print axioms ThresholdComponentScores.Instance.scoreImage_cell_constant
#check ThresholdComponentScores.Categories.category_monotone
#print axioms ThresholdComponentScores.Categories.category_monotone
#check ThresholdComponentScores.Categories.category_cutpoint
#print axioms ThresholdComponentScores.Categories.category_cutpoint
#check ThresholdComponentScores.Instance.categoryInvariant_iff_states
#print axioms ThresholdComponentScores.Instance.categoryInvariant_iff_states
#check ThresholdComponentScores.Instance.categoryInvariant_iff_endpoints
#print axioms ThresholdComponentScores.Instance.categoryInvariant_iff_endpoints
#check ThresholdComponentScores.Instance.boundary_test
#print axioms ThresholdComponentScores.Instance.boundary_test
#check ThresholdComponentScores.Instance.categoryInvariant_zero
#print axioms ThresholdComponentScores.Instance.categoryInvariant_zero
#check ThresholdComponentScores.Instance.box_mono
#print axioms ThresholdComponentScores.Instance.box_mono
#check ThresholdComponentScores.Instance.categoryInvariant_antitone
#print axioms ThresholdComponentScores.Instance.categoryInvariant_antitone
#check ThresholdComponentScores.Instance.badRadii_upward
#print axioms ThresholdComponentScores.Instance.badRadii_upward
#check ThresholdComponentScores.Instance.categoryInvariant_cell_constant
#print axioms ThresholdComponentScores.Instance.categoryInvariant_cell_constant
#check ThresholdComponentScores.Instance.categoryRadius_le_bad
#print axioms ThresholdComponentScores.Instance.categoryRadius_le_bad
#check ThresholdComponentScores.Instance.categoryRadius_eq_top_iff
#print axioms ThresholdComponentScores.Instance.categoryRadius_eq_top_iff
#check ThresholdComponentScores.Instance.RadiusCell.left_mem
#print axioms ThresholdComponentScores.Instance.RadiusCell.left_mem
#check ThresholdComponentScores.Instance.RadiusCell.representative_mem
#print axioms ThresholdComponentScores.Instance.RadiusCell.representative_mem
#check ThresholdComponentScores.Instance.RadiusCell.left_le
#print axioms ThresholdComponentScores.Instance.RadiusCell.left_le
#check ThresholdComponentScores.Instance.exists_radiusCell
#print axioms ThresholdComponentScores.Instance.exists_radiusCell
#check ThresholdComponentScores.Instance.badRadii_eq_union_bad_cells
#print axioms ThresholdComponentScores.Instance.badRadii_eq_union_bad_cells
#check ThresholdComponentScores.Instance.badCriticalEndpoints_empty_iff
#print axioms ThresholdComponentScores.Instance.badCriticalEndpoints_empty_iff
#check ThresholdComponentScores.Instance.categoryRadius_eq_top_iff_no_bad_cells
#print axioms ThresholdComponentScores.Instance.categoryRadius_eq_top_iff_no_bad_cells
#check ThresholdComponentScores.Instance.RadiusCell.exists_below_real
#print axioms ThresholdComponentScores.Instance.RadiusCell.exists_below_real
#check ThresholdComponentScores.Instance.categoryRadius_le_bad_cell_left
#print axioms ThresholdComponentScores.Instance.categoryRadius_le_bad_cell_left
#check ThresholdComponentScores.Instance.categoryRadius_eq_min_badCriticalEndpoints
#print axioms ThresholdComponentScores.Instance.categoryRadius_eq_min_badCriticalEndpoints
#check ThresholdComponentScores.Instance.finite_categoryRadius_mem_criticalDistances
#print axioms ThresholdComponentScores.Instance.finite_categoryRadius_mem_criticalDistances
#check ThresholdComponentScores.Instance.criticalDistances_card_le
#print axioms ThresholdComponentScores.Instance.criticalDistances_card_le
#check ThresholdComponentScores.Instance.finite_radius_and_boundary
#print axioms ThresholdComponentScores.Instance.finite_radius_and_boundary
#check ThresholdComponentScores.Instance.active_mono
#print axioms ThresholdComponentScores.Instance.active_mono
#check ThresholdComponentScores.Instance.componentMaximum_mono
#print axioms ThresholdComponentScores.Instance.componentMaximum_mono
#check ThresholdComponentScores.Instance.componentMultiplier_nonneg
#print axioms ThresholdComponentScores.Instance.componentMultiplier_nonneg
#check ThresholdComponentScores.Instance.componentMultiplier_mono
#print axioms ThresholdComponentScores.Instance.componentMultiplier_mono
#check ThresholdComponentScores.Instance.score_eq_sum_vertices
#print axioms ThresholdComponentScores.Instance.score_eq_sum_vertices
#check ThresholdComponentScores.Instance.score_mono
#print axioms ThresholdComponentScores.Instance.score_mono
#check ThresholdComponentScores.Instance.lowerCorner_mem
#print axioms ThresholdComponentScores.Instance.lowerCorner_mem
#check ThresholdComponentScores.Instance.upperCorner_mem
#print axioms ThresholdComponentScores.Instance.upperCorner_mem
#check ThresholdComponentScores.Instance.corner_bounds
#print axioms ThresholdComponentScores.Instance.corner_bounds
#check ThresholdComponentScores.Instance.lowerCorner_isLeast
#print axioms ThresholdComponentScores.Instance.lowerCorner_isLeast
#check ThresholdComponentScores.Instance.upperCorner_isGreatest
#print axioms ThresholdComponentScores.Instance.upperCorner_isGreatest
#check ThresholdComponentScores.Instance.corner_extrema
#print axioms ThresholdComponentScores.Instance.corner_extrema
#check ThresholdComponentScores.Instance.computeCornerReach_correct
#print axioms ThresholdComponentScores.Instance.computeCornerReach_correct
#check ThresholdComponentScores.Instance.computeCornerMin_correct
#print axioms ThresholdComponentScores.Instance.computeCornerMin_correct
#check ThresholdComponentScores.Instance.computeCornerMax_correct
#print axioms ThresholdComponentScores.Instance.computeCornerMax_correct
#check ThresholdComponentScores.Instance.computeCornerEndpoints_correct
#print axioms ThresholdComponentScores.Instance.computeCornerEndpoints_correct
#check ThresholdComponentScores.Instance.categoryInvariant_iff_corners
#print axioms ThresholdComponentScores.Instance.categoryInvariant_iff_corners
#check ThresholdComponentScores.Instance.computeBoundaryInvariant_correct
#print axioms ThresholdComponentScores.Instance.computeBoundaryInvariant_correct
#check ThresholdComponentScores.Instance.cornerBadCriticalEndpoints_eq
#print axioms ThresholdComponentScores.Instance.cornerBadCriticalEndpoints_eq
#check ThresholdComponentScores.Instance.computeCornerRadius_correct
#print axioms ThresholdComponentScores.Instance.computeCornerRadius_correct
#check ThresholdComponentScores.Instance.computeCornerRadius_some_nonneg
#print axioms ThresholdComponentScores.Instance.computeCornerRadius_some_nonneg
#check ThresholdComponentScores.Instance.computeCornerRadius_boundary_correct
#print axioms ThresholdComponentScores.Instance.computeCornerRadius_boundary_correct
#check ThresholdComponentScores.Thresholds.allowed_some_iff_bin_bounds
#print axioms ThresholdComponentScores.Thresholds.allowed_some_iff_bin_bounds
#check ThresholdComponentScores.Thresholds.exists_bin_iff
#print axioms ThresholdComponentScores.Thresholds.exists_bin_iff
#check ThresholdComponentScores.Thresholds.uncertain_allowed_iff
#print axioms ThresholdComponentScores.Thresholds.uncertain_allowed_iff
#check ThresholdComponentScores.Thresholds.stable_max_witness
#print axioms ThresholdComponentScores.Thresholds.stable_max_witness
#check ThresholdComponentScores.Thresholds.stable_max_bins_iff
#print axioms ThresholdComponentScores.Thresholds.stable_max_bins_iff
#check ThresholdComponentScores.StableSummary.support_inl
#print axioms ThresholdComponentScores.StableSummary.support_inl
#check ThresholdComponentScores.StableSummary.support_inr
#print axioms ThresholdComponentScores.StableSummary.support_inr
#check ThresholdComponentScores.StableSummary.support_nonempty
#print axioms ThresholdComponentScores.StableSummary.support_nonempty
#check ThresholdComponentScores.StableSummary.support_subset
#print axioms ThresholdComponentScores.StableSummary.support_subset
#check ThresholdComponentScores.StableSummary.supports_cover
#print axioms ThresholdComponentScores.StableSummary.supports_cover
#check ThresholdComponentScores.StableSummary.node_eq_of_mem
#print axioms ThresholdComponentScores.StableSummary.node_eq_of_mem
#check ThresholdComponentScores.StableSummary.support_connected
#print axioms ThresholdComponentScores.StableSummary.support_connected
#check ThresholdComponentScores.StableSummary.no_component_edges
#print axioms ThresholdComponentScores.StableSummary.no_component_edges
#check ThresholdComponentScores.StableSummary.graph_adj_uncertain
#print axioms ThresholdComponentScores.StableSummary.graph_adj_uncertain
#check ThresholdComponentScores.StableSummary.graph_adj_boundary
#print axioms ThresholdComponentScores.StableSummary.graph_adj_boundary
#check ThresholdComponentScores.StableSummary.mem_expand
#print axioms ThresholdComponentScores.StableSummary.mem_expand
#check ThresholdComponentScores.StableSummary.support_connected_active
#print axioms ThresholdComponentScores.StableSummary.support_connected_active
#check ThresholdComponentScores.StableSummary.mem_activeNodes
#print axioms ThresholdComponentScores.StableSummary.mem_activeNodes
#check ThresholdComponentScores.StableSummary.node_active_of_mem
#print axioms ThresholdComponentScores.StableSummary.node_active_of_mem
#check ThresholdComponentScores.StableSummary.reachable_lift
#print axioms ThresholdComponentScores.StableSummary.reachable_lift
#check ThresholdComponentScores.StableSummary.reachable_project
#print axioms ThresholdComponentScores.StableSummary.reachable_project
#check ThresholdComponentScores.StableSummary.reachable_iff
#print axioms ThresholdComponentScores.StableSummary.reachable_iff
#check ThresholdComponentScores.StableSummary.expand_component
#print axioms ThresholdComponentScores.StableSummary.expand_component
#check ThresholdComponentScores.StableSummary.expand_injective
#print axioms ThresholdComponentScores.StableSummary.expand_injective
#check ThresholdComponentScores.StableSummary.components_image_expand
#print axioms ThresholdComponentScores.StableSummary.components_image_expand
#check ThresholdComponentScores.StableSummary.expand_mem_components_iff
#print axioms ThresholdComponentScores.StableSummary.expand_mem_components_iff
#check ThresholdComponentScores.StableSummary.components_bijOn_expand
#print axioms ThresholdComponentScores.StableSummary.components_bijOn_expand
#check ThresholdComponentScores.StableSummary.support_pairwise_disjoint
#print axioms ThresholdComponentScores.StableSummary.support_pairwise_disjoint
#check ThresholdComponentScores.StableSummary.card_expand
#print axioms ThresholdComponentScores.StableSummary.card_expand
#check ThresholdComponentScores.StableSummary.sum_expand
#print axioms ThresholdComponentScores.StableSummary.sum_expand
#check ThresholdComponentScores.StableSummary.sup_expand
#print axioms ThresholdComponentScores.StableSummary.sup_expand
#check ThresholdComponentScores.Instance.summaryActive_projection
#print axioms ThresholdComponentScores.Instance.summaryActive_projection
#check ThresholdComponentScores.Instance.summaryProjection_active
#print axioms ThresholdComponentScores.Instance.summaryProjection_active
#check ThresholdComponentScores.Instance.stateMaximum_expand
#print axioms ThresholdComponentScores.Instance.stateMaximum_expand
#check ThresholdComponentScores.Instance.stateScore_eq_summaryScore
#print axioms ThresholdComponentScores.Instance.stateScore_eq_summaryScore
#check ThresholdComponentScores.Instance.summaryProjection_uncertain
#print axioms ThresholdComponentScores.Instance.summaryProjection_uncertain
#check ThresholdComponentScores.Instance.summaryProjection_stable
#print axioms ThresholdComponentScores.Instance.summaryProjection_stable
#check ThresholdComponentScores.Instance.mem_stableVertices
#print axioms ThresholdComponentScores.Instance.mem_stableVertices
#check ThresholdComponentScores.Instance.mem_inactiveVertices
#print axioms ThresholdComponentScores.Instance.mem_inactiveVertices
#check ThresholdComponentScores.Instance.mem_uncertainVertices
#print axioms ThresholdComponentScores.Instance.mem_uncertainVertices
#check ThresholdComponentScores.Instance.stable_uncertain_disjoint
#print axioms ThresholdComponentScores.Instance.stable_uncertain_disjoint
#check ThresholdComponentScores.Instance.mem_stable_union_uncertain
#print axioms ThresholdComponentScores.Instance.mem_stable_union_uncertain
#check ThresholdComponentScores.Instance.vertex_partition
#print axioms ThresholdComponentScores.Instance.vertex_partition
#check ThresholdComponentScores.Instance.inactive_state_eq_none
#print axioms ThresholdComponentScores.Instance.inactive_state_eq_none
#check ThresholdComponentScores.Instance.stable_subset_stateActive
#print axioms ThresholdComponentScores.Instance.stable_subset_stateActive
#check ThresholdComponentScores.Instance.stateActive_subset_stable_uncertain
#print axioms ThresholdComponentScores.Instance.stateActive_subset_stable_uncertain
#check ThresholdComponentScores.Instance.stateScore_eq_contractedScore
#print axioms ThresholdComponentScores.Instance.stateScore_eq_contractedScore
#check ThresholdComponentScores.Instance.stateMaximum_bounds_of_stable
#print axioms ThresholdComponentScores.Instance.stateMaximum_bounds_of_stable
#check ThresholdComponentScores.Instance.projectSummary_mem_summaryAllowed
#print axioms ThresholdComponentScores.Instance.projectSummary_mem_summaryAllowed
#check ThresholdComponentScores.Instance.glueSummary_on_support
#print axioms ThresholdComponentScores.Instance.glueSummary_on_support
#check ThresholdComponentScores.Instance.glueSummary_mem_box
#print axioms ThresholdComponentScores.Instance.glueSummary_mem_box
#check ThresholdComponentScores.Instance.glueSummary_exists
#print axioms ThresholdComponentScores.Instance.glueSummary_exists
#check ThresholdComponentScores.Instance.summaryProjection_congr_on_support
#print axioms ThresholdComponentScores.Instance.summaryProjection_congr_on_support
#check ThresholdComponentScores.Instance.exists_summary_realization
#print axioms ThresholdComponentScores.Instance.exists_summary_realization
#check ThresholdComponentScores.Instance.projectSummary_stateOf_surjOn
#print axioms ThresholdComponentScores.Instance.projectSummary_stateOf_surjOn
#check ThresholdComponentScores.Instance.scoreImage_eq_contractedImage
#print axioms ThresholdComponentScores.Instance.scoreImage_eq_contractedImage
#check ThresholdComponentScores.Instance.contractedScore_rational_lift
#print axioms ThresholdComponentScores.Instance.contractedScore_rational_lift
#check ThresholdComponentScores.Instance.projectSummary_surjOn
#print axioms ThresholdComponentScores.Instance.projectSummary_surjOn
#check ThresholdComponentScores.Instance.stateImage_eq_contractedImage
#print axioms ThresholdComponentScores.Instance.stateImage_eq_contractedImage
#check ThresholdComponentScores.Instance.summary_attained_extrema
#print axioms ThresholdComponentScores.Instance.summary_attained_extrema
#check ThresholdComponentScores.Instance.contracted_category_rational_lift
#print axioms ThresholdComponentScores.Instance.contracted_category_rational_lift
#check ThresholdComponentScores.SummaryPayload.score_of_isEmpty
#print axioms ThresholdComponentScores.SummaryPayload.score_of_isEmpty
#check ThresholdComponentScores.Instance.payload_mass_pos
#print axioms ThresholdComponentScores.Instance.payload_mass_pos
#check ThresholdComponentScores.Instance.payload_area_nonneg
#print axioms ThresholdComponentScores.Instance.payload_area_nonneg
#check ThresholdComponentScores.Instance.payload_assignments_eq
#print axioms ThresholdComponentScores.Instance.payload_assignments_eq
#check ThresholdComponentScores.Instance.payload_score_eq
#print axioms ThresholdComponentScores.Instance.payload_score_eq
#check ThresholdComponentScores.Instance.scoreImage_eq_payloadImage
#print axioms ThresholdComponentScores.Instance.scoreImage_eq_payloadImage
#check ThresholdComponentScores.Instance.payload_rational_lift
#print axioms ThresholdComponentScores.Instance.payload_rational_lift
